module.exports = (preset) => {
    let adjectivesNormal = [
        "Invincible",
        "Burning",
        "Preposterous",
        "Grumpy",
        "SuperDuper",
        "Boring",
        "Sorry",
        "Hot",
        "Used",
        "Afraid",
        "Tall",
        "Large",
        "Terrible",
        "Distorted",
        "Curious",
        "Pregnant",
        "Useful",
        "Decent",
        "Enhanced",
        "Asleep",
        "Cultural",
        "Indistinguishable",
        "Exciting",
        "Healthy",
        "Logical",
        "Popular",
        "Overdriven",
        "Unhappy",
        "Known",
        "Critical",
        "Ugly",
        "Legal",
        "Powerful",
        "Hungry",
        "Angry",
        "Aware",
        "Scared",
        "Tiny",
        "Wooden",
        "Informal",
        "Happy",
        "Strict",
        "Obvious",
        "Federal",
        "Nice",
        "Every",
        "Relevant",
        "Friendly",
        "Distinct",
        "Ancient",
        "Unlikely",
        "Odd",
        "Weak",
        "Suitable",
        "Severe",
        "Capable",
        "Unfair",
        "Lonely",
        "Entire",
        "Similar",
        "Obscure",
        "Redundant",
        "Intelligent",
        "Yellow",
        "Sinister",
        "Spectacular",
        "Mint",
        "Fuzzy",
        "Chipped",
        "Squishy",
        "Corrupted",
        "Predictable",
        "Super",
        "Sharp",
        "Junior",
        "Riveting",
        "Perfect",
        "EX",
        "Supreme",
        "Dark",
        "Volcanic",
        "Colorful",
        "Flimsy",
        "Silly",
        "Shin",
        "Denjin",
        "Surprising",
        "Optimal",
        "Suboptimal",
        "Ultra",
        "Counter",
        "Cowardly",
        "Hairy",
        "Rage",
        "Vegan",
        "Epic",
        "Turbo",
        "Undead",
        "Chill",
        "True",
        "Moody",
        "Frozen",
        "Flawless",
        "Pointless",
        "Shinku",
        "Mesatsu",
        "Terran",
        "Protoss",
        "Zerg",
        "Orcish",
        "Elvish",
        "Tarot",
        "Bohemian",
        "Arcane",
        "Mystic",
        "Light",
        "Red",
        "Crimson",
        "Garnet",
        "Ruby",
        "Blue",
        "Azure",
        "Lapis",
        "Cobalt",
        "Sapphire",
        "White",
        "Pearl",
        "Ivory",
        "Crystal",
        "Diamond",
        "Topaz",
        "Amber",
        "Jade",
        "Obsidian",
        "Emerald",
        "Fine",
        "Strong",
        "Grand",
        "Valiant",
        "Glorious",
        "Blessed",
        "Saintly",
        "Awesome",
        "Holy",
        "Godly",
        "Bronze",
        "Iron",
        "Steel",
        "Silver",
        "Gold",
        "Platinum",
        "Mithril",
        "Meteoric",
        "Weird",
        "Strange",
        "Jagged",
        "Deadly",
        "Heavy",
        "Vicious",
        "Brutal",
        "Massive",
        "Savage",
        "Ruthless",
        "Merciless",
        "Khajit",
        "Argonian",
        "Redguard",
        "Breton",
        "Nord",
        "Dunmer",
        "Altmer",
        "Falmer",
        "Bosmer",
        "Plentiful",
        "Bountiful",
        "Angels",
        "Arch-Angels",
        "Final",
        "Mandalorian",
        "Prototype",
        "Sith",
        "Jedi",
        "Battle",
        "Autobot",
        "Decepticon",
        "Primal",
        "Whovian",
        "Golgari",
        "Azorius",
        "Boros",
        "Simic",
        "Dimir",
        "Selesnya",
        "Gruul",
        "Orzhov",
        "Rakdos",
        "Izzet",
        "Infinite",
        "Eldritch",
        "Bucolic",
        "Serendipitous",
        "Angsty",
        "Death",
        "Chase",
        "Urzas",
        "Dank",
        "Borg",
        "Romulan",
        "Klingon",
        "Cardassian",
        "Jaffa",
        "Goauld",
        "Asgardian",
        "Vulcan"
    ];
    let nounsNormal = [
        "Axelord",
        "Fleaman",
        "Nutella",
        "Saiyan",
        "Turtle",
        "Ranger",
        "Whip",
        "Octopus",
        "Slayer",
        "Vampire",
        "Zombie",
        "Skeleton",
        "Zerg",
        "Terran",
        "Protoss",
        "SCP",
        "Spark",
        "Steel",
        "Rage",
        "Connection",
        "Radiator",
        "Alien",
        "Dog",
        "Cat",
        "Setup",
        "Shoryuken",
        "Fireball",
        "Fist",
        "Dolphin",
        "Force",
        "Star",
        "Bug",
        "Beard",
        "Moustache",
        "Junior",
        "Planet",
        "Mist",
        "Wolf",
        "Bat",
        "Armor",
        "Axe",
        "Sword",
        "Boss",
        "Seed",
        "Cable",
        "Soup",
        "Poem",
        "Trebuchet",
        "Cheek",
        "Girl",
        "Spawn",
        "Fortune",
        "Revolver",
        "Drawing",
        "Grocery",
        "Leader",
        "Setting",
        "Security",
        "Office",
        "Agency",
        "User",
        "Resource",
        "Policy",
        "Love",
        "Extent",
        "Week",
        "Employee",
        "Climate",
        "Unit",
        "Union",
        "Person",
        "Painting",
        "Analysis",
        "Night",
        "City",
        "Church",
        "Surgery",
        "Police",
        "Witch",
        "Finding",
        "Viper",
        "Member",
        "Patience",
        "Computer",
        "Movie",
        "Argument",
        "Virus",
        "Courage",
        "Debt",
        "Engine",
        "Tooth",
        "Wife",
        "Employer",
        "Gate",
        "Accident",
        "Warning",
        "Dinner",
        "Avocado",
        "Banana",
        "Cherry",
        "Celery",
        "Proton",
        "Neutron",
        "Apple",
        "Button",
        "Monitor",
        "Controller",
        "Potential",
        "Hadoken",
        "Justice",
        "Mew",
        "Cannon",
        "TatsumakiSenpukyaku",
        "Gohado",
        "Orc",
        "Elf",
        "Ent",
        "Spider",
        "Death",
        "Demon",
        "Goblin",
        "Wurm",
        "Spirit",
        "Horror",
        "God",
        "Devil",
        "Minotaur",
        "Blast",
        "Bus",
        "Horse",
        "Moon",
        "Executioner",
        "Assassin",
        "Druid",
        "Barbarian",
        "Sorceress",
        "Wizard",
        "Necromancer",
        "Paladin",
        "Amazon",
        "Crusader",
        "Rogue",
        "Warrior",
        "Sorcerer",
        "Angel",
        "Nephalim",
        "Evil",
        "Lunch",
        "Breakfast",
        "Artifact",
        "Enchantment",
        "Creature",
        "Planeswalker",
        "Flux",
        "Tardis",
        "Companion",
        "Hour",
        "Minute",
        "Second",
        "Day",
        "Month",
        "Year",
        "Talisman",
        "Curio",
        "Bangle",
        "Broach",
        "Spell",
        "Sorcery",
        "Mummy",
        "Werewolf",
        "Werebear",
        "Werebat",
        "Knight",
        "Soldier",
        "King",
        "Queen",
        "Rebel",
        "Mercenary",
        "Error",
        "Object",
        "Prime",
        "Sage",
        "Butcher",
        "Echo",
        "Leyline",
        "Bahamut",
        "Cactuar",
        "Tonberry",
        "Chocobo",
        "Moogle",
        "Moomba",
        "Surge",
        "Eidolon",
        "Esper",
        "Leviathan",
        "Phoenix",
        "Pikachu",
        "Charizard",
        "Xenomorph",
        "Android",
        "Jedi",
        "Sith",
        "Maverick",
        "Mandalorian",
        "Grail",
        "Card",
        "Slime",
        "Mewtwo",
        "Fireflower",
        "Mushroom",
        "Starman",
        "Mario",
        "Peach",
        "Toad",
        "Luigi",
        "Bowser",
        "Mask",
        "Ganon",
        "Materia",
        "Fairy",
        "Battletoad",
        "Kombat",
        "Portal",
        "CompanionCube",
        "Cake",
        "Dervish",
        "Kraken",
        "Meme",
        "Jaffa",
        "Goauld",
        "Stargate",
        "Zatniktel",
        "Q",
        "Cardassian",
        "Klingon",
        "Romulan",
        "Vulcan"
    ];

    let adjectivesHalloween = [
        "Scary",
        "Terrifying",
        "Spooky",
        "Eerie",
        "Horrendous",
        "Abyssal",
        "Spinechilling",
        "Bloodcurdling",
        "Chilling",
        "Horrid",
        "Horrific",
        "Horrifying",
        "Dire",
        "Dreadful",
        "Fearsome",
        "Ghastly",
        "Disturbing",
        "Unnerving",
        "Creepy",
        "Nightmarish",
        "Gruesome",
        "Grotesque",
        "Hideous",
        "Petrifying",
        "Undead",
        "Vile",
        "Evil",
        "Unsettling",
        "Incorporeal",
        "Ephemeral",
        "Haunting",
        "Frightening",
        "Graven",
        "Abhorrent",
        "Surreal",
        "Insidious",
        "Sordid",
        "Malicious",
        "Unspeakable",
        "Defiled",
        "Unscrupulous",
        "Sinister",
        "Malevolent",
        "Haunted",
        "Gory",
        "Decapitated",
        "Disemboweled",
        "Deceased",
        "Fanged",
        "Paranormal"
    ];
    let nounsHalloween = [
        "Skeleton",
        "Ghost",
        "SCP",
        "Vampire",
        "Ghoul",
        "Werewolf",
        "Zombie",
        "Phantom",
        "Monster",
        "Lich",
        "Bulette",
        "Beholder",
        "Hag",
        "Witch",
        "MindFlayer",
        "Devil",
        "Demon",
        "Fiend",
        "Alien",
        "Lich",
        "Gargoyle",
        "Abomination",
        "Construct",
        "Wendigo",
        "Wight",
        "Goblin",
        "Crone",
        "Spectre",
        "Banshee",
        "Wraith",
        "Arachnid",
        "Monstrosity",
        "Yokai",
        "Spirit",
        "Wretch",
        "Fiend",
        "Oni",
        "Kitsune",
        "Chupacabra",
        "Basilisk",
        "Horror",
        "Nightmare",
        "Cockatrice",
        "Kraken",
        "Djinn",
        "Ogre",
        "Gorgon",
        "Warlock",
        "Ooze",
        "Shedim",
        "Asura",
        "Daeva",
        "Gallas",
    ];

    let adjectivesHolidays = [
        "Snowy",
        "Merry",
        "Happy",
        "Jolly",
        "Cozy",
        "Festive",
        "Relaxing",
        "Cheery",
        "Warm",
        "Sparkly",
        "Wintry",
        "Joyful",
        "Snow",
        "Giving",
        "Celebratory",
        "Joyous",
        "Yule",
        "Frosty",
        "Jingly"
    ];

    let adjectives = [];
    let nouns = [];

    let month = new Date().getMonth() + 1;

    switch (month) {
        case 10:
            adjectives = adjectivesHalloween;
            nouns = nounsHalloween;
            break;

        case 12:
            adjectives = adjectivesHolidays;
            nouns = nounsNormal;
            break;

        default:
            adjectives = adjectivesNormal;
            nouns = nounsNormal;
            break;
    }

    let adjective = adjectives[Math.floor(Math.random() * Math.floor(adjectives.length - 1))];
    let noun = nouns[Math.floor(Math.random() * Math.floor(nouns.length - 1))];
    let number = Math.floor(Math.random() * 999);
    if (number % 100 === 69) {
        number = '69Nice';
    }

    const rando = 't.sotn.io/?';
    const adventureUrl = 'a.t.sotn.io/?';
    const casualUrl = 'c.t.sotn.io/?';
    const speedrunUrl = 's.t.sotn.io/?';
    const ogUrl = 'og.t.sotn.io/?';
    const gogUrl = 'sotn.io/?tp:guarded-og,,'
    const glitchUrl = 'g.t.sotn.io/?';
    const scavengerUrl = 'sc.t.sotn.io/?';
    const handUrl = 'eh.t.sotn.io/?';
    const batUrl = 'sotn.io/?tp:bat-master,,';
    const nimbleUrl = 'sotn.io/?tp:nimble,,';
    const lycanthropeUrl = 'sotn.io/?tp:lycanthrope,,';
    const expeditionUrl = 'sotn.io/?tp:expedition,,';
    const warlockUrl = 'sotn.io/?tp:warlock,,';

    //const bingo = 'testrunnersrl.github.io/?seed=';
    //const bingoSuffix = '&game=sotn&type=';
    //const bingospeedrunUrluffix = '&game=sotnr&type=';
    let site = '';
    let suffix = '';

    switch (preset) {
        case "og":
            site += ogUrl;
            break;
        case "guarded-og":
            site += gogUrl;
            break;
        case "speedrun":
            site += speedrunUrl;
            break;
        case "casual":
            site += casualUrl;
            break;
        case "adventure":
            site += adventureUrl;
            break;
        case "glitch":
            site += glitchUrl;
            break;
        case "scavenger":
            site += scavengerUrl;
            break;
        case "bat-master":
            site += batUrl;
            break;
        case "nimble":
            site += nimbleUrl;
            break;
        case "lycanthrope":
            site += lycanthropeUrl;
            break;
        case "expedition":
            site += expeditionUrl;
            break;
        case "warlock":
            site += warlockUrl;
            break;
        case "empty-hand":
            site += handUrl;
            break;
        default:
            site += rando;
    }

    console.log(site);

    let seedName = adjective + noun + number + suffix;
    let seedLink = 'https://' + site + seedName;

    let seed = {
        name: seedName,
        link: seedLink
    };

    return seed;
};
